### ISSUE TITLE
Graphics are broken links

### ISSUE THREAD

**Issue by stealthrabbi** [grundic/teamcity-browser-notify#1]
Broken link for image, at least in Chrome. TeamCity 10.0.3.
![image](https://cloud.githubusercontent.com/assets/1018272/21060682/a8e0c238-be16-11e6-910c-0fdd2ab37884.png)

**Comment by stealthrabbi** [comment]
The actual browser notification has the text, but no icon.

**Comment by stealthrabbi** [comment]
from browser inspector:

<img src="/plugins/teamcity-browser-notify/com/github/grundic/browser/notificator/img/permission_granted.png" align="middle">

**Comment by grundic** [comment]
@stealthrabbi, thank you for your bug report!
Will check this issue, should be some trivial error with resources.

**Comment by grundic** [comment]
Hm, strange. Could not reproduce your issue. Can you give some more information about your environment? What operating system do you use?

Can you take a look at <TEAMCITY_INSTALLATION>/webapps/ROOT/plugins/teamcity-browser-notify. It should look something like this:
```
TeamCity-10.0.3/webapps/ROOT/plugins/teamcity-browser-notify
└── com
    └── github
        └── grundic
            └── browser
                └── notificator
                    ├── img
                    │   ├── permission_denied.png
                    │   ├── permission_granted.png
                    │   └── teamcity_logo.png
                    ├── js
                    │   ├── listener.js
                    │   ├── notify.js
                    │   └── settings.js
                    └── jsp
                        ├── empty.jsp
                        └── settings.jsp

8 directories, 8 files
```

**Comment by stealthrabbi** [comment]
My directory looks like that, although my teamcity is not installed in webapps/ROOT, but instead webapps/teamcity.

**Comment by stealthrabbi** [comment]
I'm on Windows, FWIW. Is there maybe an issue with permissions on the image files?

**Comment by grundic** [comment]
Well, `webapps/teamcity` looks weird: just installed Teamcity on Windows through the installer and here is the installation path: `C:\TeamCity\webapps\ROOT`. How did you installed your version of TeamCity?

**Comment by stealthrabbi** [comment]
I just moved it from ROOT to teamcity so teamcity would be in the URL. I think I installed via the MSI before, and update by giving downloading new WAR files.

Everything else works fine with teamcity.

**Comment by grundic** [comment]
I see, you've done something like this: http://stackoverflow.com/questions/6071426/teamcity-behind-nginx-proxy.

Okay, now I understand the problem. Would try to find a solution for that.

**Comment by stealthrabbi** [comment]
no, i'm not behind a proxy. I just wanted to change the URL for the teamcity install.

Is there something in your plugin that expects the webapp to be in root?

**Comment by grundic** [comment]
There is a path to the icons, which doesn't expect custom path of Teamcity...
Have to change it [here](https://github.com/grundic/teamcity-browser-notify/blob/master/src/main/resources/buildServerResources/com/github/grundic/browser/notificator/js/settings.js#L41).

**Comment by grundic** [comment]
@stealthrabbi, fixed that in 1.0.1, please have a [look](https://github.com/grundic/teamcity-browser-notify/releases/tag/v1.0.1).
Thank you for your issue :)

**Comment by stealthrabbi** [comment]
Alright, so i've never updated a plugin before. Do i just delete the old zip from the plugins dir and replace with the new one?

**Comment by grundic** [comment]
Yep, that should be enough.

**Comment by stealthrabbi** [comment]
tested out the new version. works good. Thanks!

**Comment by grundic** [comment]
Awesome! 
Thank you as well for finding this issue.
