### ISSUE TITLE
Clicking browser notifcation takes you to a non-existant page

### ISSUE THREAD

**Issue by stealthrabbi** [grundic/teamcity-browser-notify#2]
Clicking a browser notification popup takes me to this URL:

http://MyServer/viewType.html?buildTypeId=MyBuildId

Where it should be taking me is 

http://MyServer/teamcity/viewType.html?buildTypeId=MyBuildId

Similar to issue #1 , I do not have teamcity installed as the root application in tomcat.

I get a 404 error as Tomcat doesn't have that resource:
HTTP Status 404 - /viewType.html

type Status report

message /viewType.html

description The requested resource is not available.

Apache Tomcat/7.0.59

**Comment by grundic** [comment]
Hi! Thank you for bug report!
Sorry, have not much time, so my reactions are kind of slow.. 
I'll try to check it and fix during this week.

**Comment by grundic** [comment]
Hi, @stealthrabbi!

Please have a look at release [v.1.0.2](https://github.com/grundic/teamcity-browser-notify/releases/tag/v1.0.2), where this issue should be fixed.

**Comment by stealthrabbi** [comment]
I'm now having an issue where clicking the browser notification doesn't seem to be linking to me anywhere. I don't get a new tab in chrome opening up.

**Comment by grundic** [comment]
Hi @stealthrabbi,
Now it should be definitely [fixed](https://github.com/grundic/teamcity-browser-notify/releases/tag/v1.0.3), can you please check it?

**Comment by stealthrabbi** [comment]
confirmed working with release 1.0.3. thanks!
