### ISSUE TITLE
Notifications indicating status should more clearly identify pass/fail

### ISSUE THREAD

**Issue by stealthrabbi** [grundic/teamcity-browser-notify#3]
A notification that tells me pass or fail is the same, except for the text of "succeeded" or "failed". It would be nice if the notification included an green check or red X icon if it failed, or some other kind of indicator. Or perhaps different font colors? Something distinct would make it a little friendlier.

**Comment by grundic** [comment]
Hi, @stealthrabbi!

Please have a look at release [v.1.0.2](https://github.com/grundic/teamcity-browser-notify/releases/tag/v1.0.2), where this issue should be fixed.

**Comment by stealthrabbi** [comment]
Thanks, I'll check out your 1.0.2 release. The Gif in your readme doesn't reflect the new icons, but I did look at the icons added in your commit, and i like the idea of the different states!

**Comment by stealthrabbi** [comment]
icons look good
